import type { CSSProperties } from 'react';
import { Platform, StyleSheet } from 'react-native';
import { eggeoColors } from '../tokens';

export const styles = StyleSheet.create({
  nativeBrand: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    minHeight: 44,
    transform: [{ translateY: 3 }],
  },
  nativeBrandText: {
    fontSize: 24,
    lineHeight: 30,
  },
  nativeMenu: {
    backgroundColor: eggeoColors.paper,
    borderColor: eggeoColors.border,
    borderRadius: 8,
    borderWidth: 2,
    gap: 4,
    left: 12,
    overflow: 'hidden',
    padding: 8,
    position: 'absolute',
    right: 12,
    shadowColor: '#000',
    shadowOffset: { height: 7, width: 7 },
    shadowOpacity: 0.18,
    shadowRadius: 0,
    top: Platform.OS === 'ios' ? 100 : 68,
    zIndex: 20,
  },
  nativeMenuItem: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 12,
    paddingVertical: 8,
    width: '100%',
  },
  nativeMenuItemActive: {
    backgroundColor: '#fbbf24',
  },
  nativeShell: {
    alignItems: 'center',
    backgroundColor: eggeoColors.paper,
    borderBottomWidth: 2,
    borderColor: eggeoColors.border,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    paddingBottom: 8,
    paddingHorizontal: 12,
    paddingTop: Platform.OS === 'ios' ? 50 : 18,
    zIndex: 10,
  },
});

export const webStyles = {
  brand: {
    alignItems: 'center',
    color: 'inherit',
    display: 'inline-flex',
    fontWeight: 900,
    gap: 10,
    minHeight: 64,
    textDecoration: 'none',
    transform: 'translateY(3px)',
  },
  brandText: {
    alignItems: 'center',
    fontSize: 24,
    lineHeight: 30,
  },
  dropdown: {
    alignItems: 'stretch',
    background: eggeoColors.paper,
    border: `2px solid ${eggeoColors.border}`,
    borderRadius: 8,
    boxShadow: '7px 7px 0 rgb(0 0 0 / 0.18)',
    flexDirection: 'column',
    gap: 4,
    left: 12,
    overflow: 'hidden',
    padding: 8,
    position: 'fixed',
    right: 12,
    top: 72,
    width: 'auto',
    zIndex: 30,
  },
  item: {
    alignItems: 'center',
    background: eggeoColors.paper,
    border: 0,
    borderRadius: 0,
    boxShadow: 'none',
    color: eggeoColors.ink,
    display: 'flex',
    justifyContent: 'center',
    minHeight: 48,
    padding: '8px 10px',
    textDecoration: 'none',
    width: '100%',
  },
  itemActive: {
    background: '#fbbf24',
  },
  itemText: {
    justifyContent: 'center',
    width: '100%',
  },
  links: {
    alignItems: 'center',
    display: 'flex',
    gap: 8,
    marginLeft: 'auto',
  },
  linkItem: {
    alignItems: 'center',
    border: `1px solid transparent`,
    borderRadius: 6,
    color: eggeoColors.ink,
    display: 'inline-flex',
    justifyContent: 'center',
    minHeight: 42,
    padding: '8px 10px',
    textDecoration: 'none',
  },
  linkItemActive: {
    background: '#dbeafe',
    borderColor: eggeoColors.border,
  },
  linkItemText: {
    fontSize: 16,
    lineHeight: 22,
  },
  menu: {
    alignItems: 'center',
    display: 'flex',
    marginLeft: 'auto',
    position: 'relative',
  },
  toggle: {
    backgroundColor: eggeoColors.paper,
    borderColor: eggeoColors.border,
    borderRadius: 6,
    borderWidth: 2,
    boxShadow: '3px 3px 0 rgb(0 0 0 / 0.18)',
    height: 44,
    placeItems: 'center',
    width: 44,
  },
} satisfies Record<string, CSSProperties>;
