import { eggeoColors } from '@eggeo/ui';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  authHeader: {
    marginBottom: 22,
  },
  authPanelWrap: {
    alignSelf: 'stretch',
    paddingHorizontal: 18,
    zIndex: 2,
  },
  fullPageContent: {
    alignSelf: 'stretch',
    elevation: 2,
    flex: 1,
    position: 'relative',
    zIndex: 2,
  },
  keyboard: {
    flex: 1,
  },
  mapFindButton: {
    alignItems: 'center',
    backgroundColor: '#FBBF24',
    borderColor: eggeoColors.border,
    borderRadius: 999,
    borderWidth: 3,
    bottom: 26,
    elevation: 60,
    height: 68,
    justifyContent: 'center',
    position: 'absolute',
    right: 18,
    shadowColor: '#000',
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 0.22,
    shadowRadius: 0,
    width: 68,
    zIndex: 60,
  },
  mapFindCloseButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: eggeoColors.border,
    borderRadius: 999,
    borderWidth: 2,
    height: 46,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.16,
    shadowRadius: 0,
    position: 'absolute',
    right: 0,
    width: 46,
  },
  mapFindModalContent: {
    paddingBottom: 18,
  },
  mapFindModalHeader: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    minHeight: 46,
    position: 'relative',
  },
  mapFindModalOverlay: {
    backgroundColor: 'rgba(0, 0, 0, 0.36)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  mapFindModalPanel: {
    alignSelf: 'stretch',
    backgroundColor: eggeoColors.paper,
    borderColor: eggeoColors.border,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderWidth: 2,
    elevation: 60,
    maxHeight: '88%',
    padding: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.18,
    shadowRadius: 0,
  },
  mapFindModalTitle: {
    fontSize: 30,
    lineHeight: 36,
    textAlign: 'center',
  },
  paddedFullPageContent: {
    padding: 18,
  },
  safeArea: {
    backgroundColor: eggeoColors.sky,
    flex: 1,
    position: 'relative',
  },
  scroll: {
    alignSelf: 'stretch',
    elevation: 2,
    flex: 1,
    position: 'relative',
    zIndex: 2,
  },
  scrollContent: {
    flexGrow: 1,
    gap: 18,
    paddingBottom: 180,
    paddingHorizontal: 18,
    paddingTop: 18,
  },
});
