import { Platform } from 'react-native';
import { eggeoColors } from '../tokens';

export const styles = {
  cloud: {
    backgroundColor: eggeoColors.paper,
    borderRadius: 999,
    height: 48,
    opacity: 0.7,
    position: 'absolute',
    width: 150,
    zIndex: 0,
  },
  cloudFour: {
    bottom: 78,
    opacity: 0.52,
    right: -38,
    transform: [{ scale: 0.85 }],
  },
  cloudFive: {
    left: -54,
    opacity: 0.46,
    top: '42%',
    transform: [{ scale: 0.76 }],
  },
  cloudOne: {
    left: -22,
    top: 58,
    transform: [{ scale: 0.9 }],
  },
  cloudPuffLeft: {
    backgroundColor: eggeoColors.paper,
    borderRadius: 999,
    height: 62,
    left: 24,
    position: 'absolute',
    top: -25,
    width: 62,
  },
  cloudPuffRight: {
    backgroundColor: eggeoColors.paper,
    borderRadius: 999,
    height: 74,
    position: 'absolute',
    right: 24,
    top: -34,
    width: 74,
  },
  cloudSix: {
    opacity: 0.42,
    right: -62,
    top: '56%',
    transform: [{ scale: 0.82 }],
  },
  cloudThree: {
    bottom: 176,
    left: 32,
    opacity: 0.5,
    transform: [{ scale: 0.72 }],
  },
  cloudTwo: {
    right: -18,
    top: 132,
    transform: [{ scale: 1.05 }],
  },
  hill: {
    backgroundColor: eggeoColors.grass,
    borderColor: eggeoColors.border,
    borderRadius: Platform.OS === 'web' ? 310 : 470,
    borderWidth: 3,
    height: Platform.OS === 'web' ? 1000 : 1040,
    width: Platform.OS === 'web' ? 620 : 940,
  },
  hillWrap: {
    alignItems: 'center',
    bottom: Platform.OS === 'web' ? -880 : -650,
    height: Platform.OS === 'web' ? 1000 : 1040,
    left: Platform.OS === 'web' ? 0 : -320,
    overflow: 'visible',
    position: 'absolute',
    right: Platform.OS === 'web' ? 0 : -320,
    zIndex: Platform.OS === 'web' ? 1 : 0,
  },
  skyScene: {
    alignItems: 'center',
    backgroundColor: eggeoColors.sky,
    flex: 1,
    justifyContent: 'center',
    minHeight: '100%',
    overflow: 'hidden',
    position: 'relative',
    width: '100%',
  },
} as const;
