import { eggeoColors } from '@eggeo/ui';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  eggMarker: {
    alignItems: 'center',
    backgroundColor: eggeoColors.paper,
    borderColor: eggeoColors.border,
    borderRadius: 999,
    borderWidth: 2,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  emptyMap: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: 18,
  },
  eventBar: {
    elevation: 6,
    left: 18,
    position: 'absolute',
    right: 18,
    top: 18,
    zIndex: 4,
  },
  eventPicker: {
    width: '100%',
  },
  findButton: {
    alignItems: 'center',
    backgroundColor: '#FBBF24',
    borderColor: eggeoColors.border,
    borderRadius: 999,
    borderWidth: 3,
    bottom: 24,
    elevation: 8,
    height: 64,
    justifyContent: 'center',
    position: 'absolute',
    right: 18,
    shadowColor: '#000',
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 0,
    width: 64,
    zIndex: 7,
  },
  findModalContent: {
    paddingBottom: 18,
  },
  findModalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  findModalOverlay: {
    backgroundColor: 'rgba(0, 0, 0, 0.36)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  findModalPanel: {
    alignSelf: 'stretch',
    backgroundColor: eggeoColors.paper,
    borderColor: eggeoColors.border,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderWidth: 2,
    elevation: 12,
    maxHeight: '88%',
    padding: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.18,
    shadowRadius: 0,
  },
  findModalTitle: {
    flex: 1,
    fontSize: 30,
    lineHeight: 36,
  },
  map: {
    flex: 1,
  },
  popover: {
    bottom: 102,
    elevation: 7,
    left: 18,
    maxHeight: '48%',
    position: 'absolute',
    right: 18,
    zIndex: 6,
  },
  popoverContent: {
    gap: 14,
  },
  popoverPanel: {
    maxHeight: '100%',
  },
  screen: {
    flex: 1,
  },
  status: {
    left: 18,
    position: 'absolute',
    right: 18,
    top: 82,
  },
});
